id: P009083
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1EE69
  title: བདེ་གཤེགས་བདུན་གྱི་མཆོད་པའི་ཆོག་བསྒྲིགས་ཡིད་བཞིན་དབང་རྒྱལ། ༼སོག་ཡིག༽
  author: ''
  volumes:
    48f5ed5cd72c47e994f7af44253e167e:
      image_group_id: I1KG17002
      title: ''
      volume_number: 1
      total_pages: 201
      base_file: v001.txt
