id: I4F3C3277
legacy_id: P009083
ocr_import_info:
  bdrc_scan_id: W1EE69
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T15:11:53'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:51:23.680950+00:00'
last_modified: 2022-08-31 03:51:47.041276
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1EE69
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1EE69
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བདེ་གཤེགས་བདུན་གྱི་མཆོད་པའི་ཆོག་བསྒྲིགས་ཡིད་བཞིན་དབང་རྒྱལ། ༼སོག་ཡིག༽
  author: ཏཱ་ལའི་བླ་མ ༠༥་ངག་དབང་བློ་བཟང་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.5885324193867303
  ocr_word_median_confidence_index: 0.5799999833106995
quality: null
bases:
  I1KG17002:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17002
      total_pages: 201
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG17002.txt
    statistics:
      ocr_word_median_confidence_index: 0.5799999833106995
      ocr_word_mean_confidence_index: 0.5885324193867303
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
